### PR TITLE
Use buildx to build multi architecture images

### PR DESCRIPTION
**Pull request by austinhallett**

### CODE REVIEW

**Comment by austinhallett** [comment]
Note this PR is still a WIP but I did notice that there was another PR wit a similar goal opened here https://github.com/crops/yocto-dockerfiles/pull/86#ref-commit-211f823
I am wondering if the team prefers to use the shell script, or the gha workflow.

At the end of the day, I do not personally care how I get arm containers, but I am in dire need. Let me know how I can assist in moving this effort forward.

**Comment by moto-timo** [comment]
> Note this PR is still a WIP but I did notice that there was another PR wit a similar goal opened here [#86 (reference)](https://github.com/crops/yocto-dockerfiles/pull/86#ref-commit-211f823) I am wondering if the team prefers to use the shell script, or the gha workflow.
> 
> At the end of the day, I do not personally care how I get arm containers, but I am in dire need. Let me know how I can assist in moving this effort forward.

In the history of this project, we have already switched from Travis CI to GitHub Actions. We expect the project to live beyond GitHub Actions to the next shiny thing. The way to avoid that vendor lock-in is with the shell scripts.

**Comment by moto-timo** [comment]
Please please please stop making the whitespace changes. It is extremely difficult to review.

**Comment by moto-timo** [comment]
I will not proceed with review until you squash the commits and remove the whitespace changes. Make sure you are enabling GitHub Actions on your fork and that you are testing the workflow.

**Pull request closed without merging**
